### PR TITLE
create flow.R and make trajectory.R depend on it

### PR DESCRIPTION
**Pull request by kidusasfaw**
unit-tested trajectory by making sure trajectory(ricker()) looks like what it should.

### CODE REVIEW

**Comment by kingaa** [comment]
@kidusasfaw: Excellent work and very fast!  I am working on merging this in, which is not very hard.

**Question:** the `rprocess` interface takes the start-time from `times[1]` and by default returns xstart as the first slice of the result.  If allows `offset>0` in case one wants to change the return behavior.  In the interest of consistency of interface, one could do the same thing for `flow`, obviating the need for the `tstart` argument.  Do you see any downsides to this?

**Comment by kidusasfaw** [comment]
Thanks, Aaron!

Yes, the offset idea makes a lot of sense. I can give that a crack and make
another PR.

Kidus

**Comment by kingaa** [comment]
Hi Kidus,

This is up and working as of version 2.0.10.0.  I'm unhappy with some inefficiency in the coding, but that will have to wait for awhile.  In particular, it is not clear that the `times`, `offset` parameterization I insisted on is actually better than the `times`, `t0` parameterization you originally introduced....  This shouldn't be a big problem for your needs however: at most you'll have to change your call to 'flow'.

**Comment by kidusasfaw** [comment]
Sounds good, Aaron. Let me know which of the two ways you end up deciding
is better. The times and tstart way does less work, but I also see your
point about interface consistency.

**Pull request merged**
